
"$schema" = "https://starship.rs/config-schema.json"

format = """
[â•­â”€â”€](bold bright-cyan)\
[î‚²](fg:#002B36)\
[$os](bg:#002B36 fg:#00FFFF)\
[î‚²](fg:#005f87 bg:#002B36)\
[ğŸ”· $username@$hostname](fg:#002B36 bg:#005f87 bold)\
[î‚²](fg:#268BD2 bg:#005f87)\
$directory\
([î‚°](fg:prev_bg bg:#2AA198)\
$git_branch$git_status)\
([î‚°](fg:prev_bg bg:#B58900)\
$golang\
$nodejs\
$bun\
$deno\
$rust\
$python\
$ruby\
$lua)\
([î‚°](fg:prev_bg bg:#859900)\
$package)\
([î‚°](fg:prev_bg bg:#D33682)\
$aws\
$azure\
$gcloud\
$kubernetes)\
([î‚°](fg:prev_bg bg:#6C71C4)\
$docker_context)\
[î‚°](fg:prev_bg bg:#002B36)\
$time\
[($shell)](bg:#002B36 fg:#00FFFF bold)\
[î‚°](fg:#002B36)\
[$line_breakâ”‚](bold bright-cyan)\
[$line_breakâ•°â”€â”€$character ](bold bright-cyan)\
"""

continuation_prompt = "[â•°â”€â”€â¯ˆâ¯ˆ ](bold bright-cyan)"
command_timeout = 1000

[line_break]
disabled = false

[character]
success_symbol = "[â¯ˆâ¯ˆ](bold bright-cyan)"
error_symbol = "[â¯ˆâ¯ˆ](bold bright-red)"

[os]
format = "[ $symbol]($style)"
style = "fg:#002B36 bg:#00FFFF"
disabled = true 

[hostname]
ssh_only = true
style = "bg:#005f87 fg:#002B36 bold"
format = "[ $hostname ]($style)"

[username]
show_always = true
style_user = "bg:#005f87 fg:#002B36 bold"
style_root = "bold bg:#005f87 fg:#002B36"
format = "[ ğŸ‘¤ ($user) ]($style)"
disabled = true

[directory]
style = "bg:#268BD2 fg:#002B36"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ğŸ“"
"Downloads" = "â¬‡ï¸"
"Music" = "ğŸµ"
"Pictures" = "ğŸ–¼ï¸"

[git_branch]
style = "bg:#2AA198"
format = "[[ ğŸ›°ï¸ $branch ](fg:#002B36 bg:#2AA198)]($style)"
truncation_length = 25

[git_status]
style = "bg:#2AA198"
format = "[[($all_status$ahead_behind )](fg:#002B36 bg:#2AA198)]($style)"

[shell]
disabled = true 
style = "fg:#00FFFF bg:#002B36 bold"

[time]
disabled = false
time_format = "%H:%M"
style = "fg:#00FFFF bg:#002B36"
format = "[$time](fg:#00FFFF bg:#002B36)"


[package]
style = "fg:#002B36 bg:#859900"
format = "[ $symbol$version ]($style)"

[aws]
style = "bg:#D33682"
format = "[[ â˜ï¸ $profile ](fg:#002B36 bg:#D33682)]($style)"

[azure]
disabled = false
style = "bg:#D33682"
format = "[[ â˜ï¸ $subscription ](fg:#002B36 bg:#D33682)]($style)"

[gcloud]
style = "bg:#D33682"
format = "[[ â˜ï¸ $account ](fg:#002B36 bg:#D33682)]($style)"

[kubernetes]
disabled = false
style = "bg:#D33682"
format = "[[ â˜ï¸ $context ](fg:#002B36 bg:#D33682)]($style)"

[docker_context]
style = "bg:#6C71C4"
format = "[[ ğŸ³ $context ](fg:#002B36 bg:#6C71C4)]($style)"

[ruby]
style = "fg:#002B36 bg:#B58900"
format = "[ ğŸ’ $version ]($style)"

[rust]
style = "fg:#002B36 bg:#B58900"
format = "[ ğŸ¦€ $version ]($style)"

[golang]
style = "fg:#002B36 bg:#B58900"
format = "[ ğŸ¹ $version ]($style)"

[lua]
style = "fg:#002B36 bg:#B58900"
format = "[ ğŸŒ™ $version ]($style)"

[bun]
style = "fg:#002B36 bg:#B58900"
format = "[ ğŸ $version ]($style)"

[nodejs]
style = "fg:#002B36 bg:#B58900"
format = "[ ğŸŸ¢ $version ]($style)"
detect_files = ["package.json", ".node-version", "!bunfig.toml", "!bun.lockb"]

[deno]
style = "fg:#002B36 bg:#B58900"
